# Generated by Django 2.2 on 2019-04-16 15:01

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('coded', '0003_auto_20190416_1456'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Info',
            new_name='UserInfo',
        ),
    ]
