# Generated by Django 2.2 on 2019-04-24 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coded', '0007_auto_20190424_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='phone_number',
            field=models.ManyToManyField(blank=True, null=True, to='coded.PhoneNumber'),
        ),
    ]
