# Generated by Django 2.2 on 2019-04-25 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coded', '0008_auto_20190424_1848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='phone_number',
            field=models.ManyToManyField(to='coded.PhoneNumber'),
        ),
    ]
